meta_product_name: "Foundaters"
meta_title: "Foundaters - Network does work"
meta_description: "Le virtuel a ses limites. Rencontrez dans la vie réelle des entrepreneurs qui vous correspondent pour échanger autour d'un verre ! (ou deux)"
meta_image: "linkedin-new.png" # should exist in `app/assets/images/`
twitter_account: "@foundaters_twitter_account"   # required for Twitter Cards
